### ISSUE TITLE
Measurements Questions Draft

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot-containers#113]
# Containers Metrics draft
Do people use these things? How much and what for?  Retained use…

* Do people who use the containers feature continue to use it? So retention is defined as opening one container tab and then opening a second container tab.
	* displayed as a cohort table by day then week
* What containers do people use
	* bar graph of the most commonly named container tabs.
* How do people create new container tabs?
	* x = time y = creations by entry point ( new tab or toolbar)
* Do people sort tabs? (Speaks to desire for organizational tooling)
	* x = time y = sorts events
	* x = time y = average number of tabs on sort
	* x = time y average number of container types displayed on sort
* 	Do people hide containers?
	* x = time, y = hide events per container tab creation events
* Do people pop containers into new windows?
	* x = time, y = move to new window events per container tab creation events

**Comment by johngruen** [comment]
@clouserw, Ilana and I will review and finalize

**Comment by bakulf** [comment]
I would like to add:

- How often do they use containers? (always opened or just for quick tasks?)
- Do they PIN container tabs?
- How often do the change the URLs in a container tab? (I want to know if users associate containers-domain, for instance: 1 container for facebook, 1 container for twitter, etc...) - maybe here we have to anonymize data client-side.

**Comment by groovecoder** [comment]
@TanviHacks is going to review this list and comment.

**Comment by TanviHacks** [comment]
More metrics listed in #99

**Comment by TanviHacks** [comment]
Replying to John's first comment -
    Do people who use the containers feature continue to use it? So retention is defined as opening one container tab and then opening a second container tab.
        displayed as a cohort table by day then week
*Note that some users may use a container once a month (ex: banking).  So we should measure by number of containers open at a time, instead of whether container X was opened every day.

    What containers do people use
        bar graph of the most commonly named container tabs.
*We can show a bar graph of usercontextids, but I don't think we can actually disclose the names of containers.  Showing usercontextid may also tell us something about how many containers were created, if lots of containers have been created and then deleted.

**Comment by TanviHacks** [comment]
More questions.  Some my own, some taken from other issues
* How many containers are hidden at one time?
* How many containers are open at a time
* How many containers are created by a user (we could count containers per user every week)
* How many containers are deleted by a user (we could count containers deleted per user every week)
* Every week, we could record a timestamp of the last access to all containers a user has.  This will tell us something like 1) user has a few containers they user all the time, 2) user has a few containers they never use, 3) user has a few containers they use often and a few they use rarely.

* What is the average lifespan of a container tab?  Is that longer or shorter than a regular tab? (if we don't have data on the latter, the former probably isn't worth gathering data on since we will have nothing to compare it to).

* How often are hidden containers restored.  Count the number of hidden events vs the number of restore events.  You would expect a few more hides than restores, but the number shouldn't be drastically different.

* What is the length of time between hide and restore.

More to come.

**Comment by groovecoder** [comment]
> * How many containers are hidden at one time?
> * How many containers are open at a time
Where "containers" means "containers with at least 1 tab" ?

> * How many containers are created by a user (we could count containers per user every week)
Covered by the ['container-add-container' event](https://github.com/mozilla/testpilot-containers/pull/140/files#diff-683a405c5c005542f9e848b827fe0765R113)

> * How many containers are deleted by a user (we could count containers deleted per user every week)
Covered by the ['container-add-container' event](https://github.com/mozilla/testpilot-containers/pull/140/files#diff-683a405c5c005542f9e848b827fe0765R104)

> * Every week, we could record a timestamp of the last access to all containers a user has.  This will tell us something like 1) user has a few containers they user all the time, 2) user has a few containers they never use, 3) user has a few containers they use often and a few they use rarely.
All telemetry event pings include a timestamp, so we can do histogram reporting by day, week, etc. And this is covered by the [`container-tab-opened` event](https://github.com/mozilla/testpilot-containers/pull/140/files#diff-683a405c5c005542f9e848b827fe0765R71) which includes the `container-name`.

> * What is the average lifespan of a container tab?  Is that longer or shorter than a regular tab? (if we don't have data on the latter, the former probably isn't worth gathering data on since we will have nothing to compare it to).
It looks like we only have [`TAB_OPEN_EVENT` data for regular tabs in Telemetry](https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2017-01-25&keys=__none__!__none__!__none__&max_channel_version=release%252F51&measure=SCALARS_BROWSER.ENGAGEMENT.TAB_OPEN_EVENT_COUNT&min_channel_version=null&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2017-01-18&table=0&trim=1&use_submission_date=0). I'll ask data team if we have data somewhere else though.

> * How often are hidden containers restored.  Count the number of hidden events vs the number of restore events.  You would expect a few more hides than restores, but the number shouldn't be drastically different.
This is covered by the [`container-show-tabs` event](https://github.com/mozilla/testpilot-containers/pull/140/files#diff-683a405c5c005542f9e848b827fe0765R141) And since we're also counting `container-hide-tabs` events, we will be able to measure the ratio of hidden vs. restored.

> * What is the length of time between hide and restore.
Every event ping has a timestamp, so we will be able to measure the duration between hide & restore.

**Comment by groovecoder** [comment]
Please add any more comments ASAP - we need to start implementing tomorrow. We can add telemetry later, too ... doesn't have to be perfect up front.

**Comment by groovecoder** [comment]
We do **NOT** have avg. tab lifespan data for regular tabs, so let's ignore that for now.

**Comment by groovecoder** [comment]
Note: it sounds like we **DO** have something like "tab open event count" and "uri counts". So if we wanted to measure tab-engagement as uris-opened-per-tabs instead of lifespan, we could probably do that.

**Comment by jonathanKingston** [comment]
@groovecoder any chance we could work out number of origins per container and how often the container themselves are used? I think that might give better metrics on if banking is important if infrequently used per origin but still over the lifetime of the experiment used at the end?

**Comment by groovecoder** [comment]
So, distinct-origins-per-container measured ... when? When the container tabs are hidden/shown? In the interest of lean data, we should avoid a continuously running background process that does nothing but send Telemetry pings all the time.

**Comment by TanviHacks** [comment]
>         How many containers are open at a time
> 
> Where "containers" means "containers with at least 1 tab" ?
> 
Yes.  So if Shopping, Banking, and Personal are open, we record 3.  I don't think we shoudl count default; I think in most cases default will be open.  And then when analyzing the results we will debate about whether a user with 2 containers open had 2 containers open, or if one was default

**Comment by TanviHacks** [comment]
>         Every week, we could record a timestamp of the last access to all containers a user has. This will tell us something like 1) user has a few containers they user all the time, 2) user has a few containers they never use, 3) user has a few containers they use often and a few they use rarely.
> 
> All telemetry event pings include a timestamp, so we can do histogram reporting by day, week, etc. And this is covered by the container-tab-opened event which includes the container-name.

Will this give us per user information?  So say we have 4 users:
*user 1 uses 3 containers every day.
*user 2 uses 1 container every week, and 2 other containers every other week
*user 3 uses 2 container every day, and 1 other containers every week.
*user 4 uses 1 container every month (doesn't use the feature much if at all)

If we can identify by user, we can see that some use it all the time, and some need it once in a while.  But if we bundle all these events together (and can't measure per user), it doesn't give us a good idea of how the feature is used.

Does that make sense?

**Comment by TanviHacks** [comment]
>         How often are hidden containers restored. Count the number of hidden events vs the number of restore events. You would expect a few more hides than restores, but the number shouldn't be drastically different.
> 
> This is covered by the container-show-tabs event And since we're also counting container-hide-tabs events, we will be able to measure the ratio of hidden vs. restored.

Is this measured by user?

**Comment by TanviHacks** [comment]
> Note: it sounds like we DO have something like "tab open event count" and "uri counts". So if we wanted to measure tab-engagement as uris-opened-per-tabs instead of lifespan, we could probably do that.

We could try.  But I don't think it makes sense to compare this to uris in default tabs.  The Container may be used for very specific things - maybe its open all the time at gmail.  While a default tab may be used to visit 50 different uris in the same lifespan.  So maybe we punt on this.

**Comment by jonathanKingston** [comment]
@groovecoder 

> So, distinct-origins-per-container measured ... when?

I think we could do distinct-origins-per-container measured per session or over a period of days perhaps?
Other ideas:
- Number of containers opened per session, number of all containers
- Times a container was opened over a 30 day period
- Container names unopened in a 30 day period
- % of containers opened over 30 day period

**Comment by TanviHacks** [comment]
In some cases, things are reported by pings at random times or every 24 hours.  In such cases I'm not sure we can tie them together for a single user (but I could be wrong about this, maybe their is a unique identifier).  But in other cases, the browser may collect data for a longer period of time and report it and that way we can get data per user.  30 days may be too long, since the experiment is only 6-8 weeks.  So maybe weekly would be better.

**Comment by TanviHacks** [comment]
@groovecoder Do you want to discuss this further tomorrow in a meeting?  My day looks pretty horrible tomorrow, but maybe we could do a phone call.

**Comment by groovecoder** [comment]
Telemetry data **DOES HAVE** a UUID field, so we should be able to tie pings for single users together with GROUP BY UUID in our queries.

A lot of our questions are overlapping now, and it sounds like we don't have more specific actionable questions yet. So I'm going to call this draft "final" in that we're ready to have someone from the data team review it.

I suggest we **DON'T** send any pings by periods (i.e., every X minutes/hours), because we would miss data and would never be sure if the data was accurate. E.g., a user opens a tab in a container, opens 2 tabs in another, hides the original container tab, and then closes them all in the space of 2 minutes. If our interval is 5 minutes we would miss all of those states, and if our interval is much smaller it will be a flood.

But I'll double-check that tactic with someone from the data team.

**Comment by groovecoder** [comment]
Closing as we've got metrics.md and telemetry probes merged into the codebase now. Any other measurements questions can be follow-up issues.
