### ISSUE TITLE
listing tabs via ">" doesn't always work when moving container tabs around

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#179]
When you move a container tab into it's own separate window, and than reattach it back into the original window, the ">" next to that particular container will be greyed out even though there's a tab opened that's using that particular container.

Reproduced using the following:
* latest commit 3a2e351661c4a4968fa142ee3afc4bea262f1a04
* containers_experiment-0.0.3-fx.xpi

STR: (assumes you have the latest test pilot installed)

> Example: https://youtu.be/fIDd4lfyumg

* open a personal container and load any website, I used reddit.com
* detach the personal container into it's own separate window
* reattach the personal container into the original window
* click on the "Container" button and attempt clicking in ">"

**Comment by groovecoder** [comment]
@bakulf I was able to fix this by removing this check from `_remapTabsIfMissing`:
```
if (userContextId in this._identitiesState) {
      return;
}
```
But are we worried that iterating over tabs will cause performance issues?

**Comment by bakulf** [comment]
If you remove those tabs:
1. hidden tabs are gone - this in theory should not be a problem per-se, because we should not have hidden tabs when we do this operation.
2. we are hiding the 'real' bug: why don't we have the right openedTabs value in this._identitysState[usercontextId] ? It seems that we receive a 'close' tab notification and not the 'open' tab. This could explain why openedTab is == 0. I would debug the correct sequence of close/open events.

**Comment by groovecoder** [comment]
@bakulf: I think we're missing this event because it's at the platform level? I.e., Dragging the tab to create the window isn't picked up by our ContextualIdentity module?

**Comment by bakulf** [comment]
I debugged this issue a bit and the issue is this: when a tab is moved to a new window, we correctly receive a 'open' tab event and then a 'close' tab event. But the opened tab, before the swapping of the docShell doesn't have userContextId set, so, for us, that is not a container tab.
I'm working on it.
