### ISSUE TITLE
underlines aren't initially being created for new custom container tabs

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/testpilot-containers#199]
Custom containers aren't initially getting the underline UI when creating new tabs. I've managed to reproduce this under macOS/Windows. If you detach/reattach the tab, the underline will appear appear correctly.

CCing @jonathanKingston & @johngruen as per the findings in #195 

> Example: https://youtu.be/tzZTYpBU3Mg

<img width="808" alt="screen shot 2017-02-16 at 6 26 55 pm" src="https://cloud.githubusercontent.com/assets/2602313/23046081/9719d43c-f475-11e6-88e3-0a780317c60d.png">

**Comment by jonathanKingston** [comment]
This doesn't seem related to the styling at all actually. The tabs are getting the hex colour value to the tab which has been noticed in other issues.

This can be fixed by mapping the colours in the CSS file however it would be better to fix this properly as it could be an indication of other data not being mapped correctly also.

**Comment by bakulf** [comment]
This has been fixed by one of my latest commit.
