### ISSUE TITLE
Moving Container tabs to a new window breaks Pageshot, Pulse add-ons and the Test Pilot website

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/testpilot-containers#242]
[Notes]:
- If the Test Pilot website is also moved this way, refreshing the page with F5 and address bar button no longer work. And if you refresh the page using the context menu, the all installed experiments no longer appear enabled.
- It seems that moving the tabs in a new container window causes Pageshot to hit [issue #1655.](https://github.com/mozilla-services/pageshot/issues/1655)
- And the same thing happens in Pulse's case, where it hits [issue #120](https://github.com/mozilla/pulse/issues/120) . However, the Pulse icon does not appear after a refresh. 

[Affected versions]:
- Firefox 51.0.1
- Containers 0.9.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Containers add-on is installed on a new clean profile.
- Pulse and Pageshot are also installed on the same profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://en.wikipedia.org/wiki/Main_Page and open a few links in container tabs. (eg. Personal)
3. Click the "Containers" button from the browser toolbar.
4. Click the arrow next to the previously used container and choose to "Move tabs to a new window".
5. Observe the URL bar.
6. Click the "Pageshot" button from the browser toolbar and observe the behavior.

[Expected results]:
- Step 5. The Pulse icon is displayed in the URL bar.
- Step 6. The Pageshot overlay covers the entire screen.

[Actual results]:
- Step 5. The Pulse icon is no longer displayed in the URL bar.
- Step 6. The Pageshot overlay does not appear on the screen and after a while it shows an error.

[Additional Notes]:
- Here is a screen recording with the issue https://goo.gl/E9rgJv.

**Comment by 6a68** [comment]
This bug sounds really bad, but I actually don't think it's anything to do with the containers addon.

The pulse and pageshot bugs are both symptoms of the same bug with the sdk tabs library: sdk/tabs loses track of tabs if the parent window changes.

Moving tabs to a new window without the containers addon would have the same effect.

I'd actually suggest we close this as invalid, since it's just uncovering known bugs that affect the other two addons.

**Comment by groovecoder** [comment]
@6a68 looks like @johngruen made a Test Pilot change to warn users about this behavior. But where would we file issues or bugs for the sdk tabs library losing track of tabs when parent window changes? Would like to know that issue is tracked somewhere.

**Comment by 6a68** [comment]
@groovecoder When I asked andym about this, he suggested just moving to the WebExtension tabs APIs instead. Those (new, maintained) APIs should be able to do what you're currently doing with the sdk/tabs code: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/

**Comment by groovecoder** [comment]
A few issues ...

1. We won't be able to use `browser.tabs.create` until Fx 52 - when we gain support for opening a tab with [`cookieStoreId` parameter](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create#Parameters).

So, maybe we disabled the "move tabs to new window" feature until Fx 52 is in release, and then we bump the min Firefox version from 51 to 52? What happens when we update the min version?

2. We would also need to call `browser.tabs.create` from within our SDK `index.js` code when the user clicks to open a new tab thru the tab bar.

Is there any Embedded WebExtensions add-on code that calls WebExtensions `browser.*` APIs from within SDK code?

**Comment by bakulf** [comment]
Me and @groovecoder have discussed this issue on IRC. We will proceed in parallel: he will try to see if this issue can be fixed by porting part of this addon to webExtension APIs.

At the same time I want to see why those addons break. At the moment it seems that they are just buggy code and they are not able to deal with tab-moving. If this is the case, there is nothing we can do in this code.

I understand that Container addon exposes the tab-moving as a key feature, and we should find a quick fix, but, can this fix be in those addons? Can somebody working on those addons work on this bug and release a new version for this week?

**Comment by groovecoder** [comment]
Trying a little bit of `browser.tabs.move()` magic to make this work. But the `sdk/tabs` ids are not reliably matched with `browser.tabs` ids. ... May have to give up soon ...

**Comment by bakulf** [comment]
This is the implementation of browser.tabs.move():
https://dxr.mozilla.org/mozilla-central/source/browser/components/extensions/ext-tabs.js#612
as you can see, internally it uses adoptTab() exactly how we do. I don't think that moving the current code to browser.tabs.move() fixes the issue.

**Comment by SoftVision-PaulOiegas** [comment]
As an update. This also affects some of the future functionality of the graduated NoMore404s experiment that will be found in AMO.

**Comment by groovecoder** [comment]
@SoftVision-PaulOiegas I think @bakulf is right - this is a lower-level bug that will affect many things. I will try to disable our "move tabs" feature if the user has incompatible experiments installed.

@bakulf - is there a bug or issue to fix the `adopTab()` bug already? Do you know where/how to file it?

**Comment by groovecoder** [comment]
https://github.com/mozilla/testpilot-containers/commit/b15fd5c9c4cd18ed35f9d636e14027d7d45f4d8b contains the first commit for this. But https://github.com/mozilla/testpilot-containers/commit/b15fd5c9c4cd18ed35f9d636e14027d7d45f4d8b#diff-0effdbf34829f2ab5dac6ed4d8906066R312 runs up against [a WebExtensions bug where pageAction pop-ups aren't displaying tooltips](https://bugzilla.mozilla.org/show_bug.cgi?id=1269421) 😢 Trying to think of a work-around ...

**Comment by groovecoder** [comment]
I didn't call it fixed in the commit message, because I worked *around* it rather than fixing it. But if you have one of the incompatible experiments installed, we now show an incompatibility message and disable the "Move" feature in the pop-up.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Containers add-on (version 1.0.1). If either/both Pageshot and Pulse are enabled the "Move to a new window" option is unavailable.
I've even tried to work around that function using the Hide/Show option, but both "affected" add-ons work as expected.
