### ISSUE TITLE
All hidden tabs are displayed when a new tab to the same container is opened

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/testpilot-containers#290]
**[Affected versions]:**
-Firefox 51.0.1 and up
-Containers Experiment 1.0.1

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Containers Experiment (v1.0.1) is installed on a Firefox new profile.

**[Steps to reproduce]:**
1. Open Firefox with the profile from prerequisites.
2. Open one or two websites in the same container.
3. Click on "Containers" button from the toolbar.
4. Click one ">" More button for the container in which are opened the tabs.
5. Click "Hide this container" button.
6. Hover the mouse cursor over the "+" Open New Tab button from tabs area and select to open a new container tab identical to the one that has the hidden tabs.

**[Expected result]:**
- A container tab is opened for the selected container.

**[Actual result]:**
- All hidden tabs for that container are opened plus the new one.

![all tabs are opened](https://cloud.githubusercontent.com/assets/9248513/23414844/f45aca92-fde5-11e6-9e4d-8b7cbb7eed38.gif)

**Comment by bakulf** [comment]
Yes, this is wanted. We don't want to support hidden an shown tabs at the same time.

**Comment by groovecoder** [comment]
Desired behavior (or now ... until more users ask for alternative behavior).

**Comment by SoftVision-PaulOiegas** [comment]
Ok, but consider this scenario. You have lots of hidden pages in a specific container (eg: 50) and you want to open a new tab of that container. This means that all the hidden tabs are opened and loaded for just one new tab. Wouldn't this affect A LOT the user experience and browser performance since it will take a lot of time to load each and every hidden page ? Because the add-on also loads the page content, not only displays them as the "Remember tabs and windows from last session" option does.

Also, probably the users will use the option to hide personal tabs because he doesn't want others to see those tabs. Forcing all of them to be opened when user opens a new tab will automatically expose those tabs. 

In my opinion, none of this is right, but hey, maybe it's just me...
