### ISSUE TITLE
Activity in pinned container tabs masks the group colour

### ISSUE THREAD

**Issue by davehunt** [mozilla/testpilot-containers#305]
When a container tab is pinned and has activity, the colour of the container group is harder to see.

Before activity:
![screen shot 2017-03-02 at 12 06 09](https://cloud.githubusercontent.com/assets/122800/23506623/13f72fec-ff41-11e6-80da-2251987f432b.png)

After activity:
![screen shot 2017-03-02 at 12 05 50](https://cloud.githubusercontent.com/assets/122800/23506641/22c1b010-ff41-11e6-83cb-31031976a2f6.png)

**Comment by groovecoder** [comment]
Nice catch.

**Comment by ChenMorpheus** [comment]
@groovecoder 
Sorry for the late reply. After several mockups we tried, we decided to keep it the way it is. There are several reasons why:
 
1. The activity badge is a temporary status since it disappears right after clicked. 
2. We could not find scenarios which users want to check which container it is but still leave the activity badges on. 
3. To keep it consistent with other container tabs, we do not suggest moving or changing the container bar design. 
4. Project Photon (Firefox visual refresh) is considering to remove or redesign the activity badge.

Please let us know if still any questions, thanks.

**Comment by groovecoder** [comment]
Thanks for the report, @davehunt, and thanks for digging into it @ChenMorpheus. 

I'll close this for now. If someone can post a scenario where the users want to check which container a pinned tab is while leaving its activity badge on, please comment back here.
