### ISSUE TITLE
51 -> 52 support issues

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/testpilot-containers#33]
- [ ] As we don't have custom containers support in 51 there isn't the ability to set the new containers to anything other than the standard 4 icons. I think however I have not checked we can support new containers with different names however they would be all the same icons.
- [ ] Edit containers button would have to be conditional if we can't support new containers
  - it certainly won't be able to go to about:preferences#containers as it doesn't exist.
- [ ] Long press new tab button

**Comment by TanviHacks** [comment]
I think we have to use a traditional SDK to shoe in the mozilla-central features that exist in the 52 but not 51.  Per baku, the possibilities of an addon SDK are pretty endless, they are just more complicated to write and hacky.

**Comment by TanviHacks** [comment]
@bakulf ^^

**Comment by bakulf** [comment]
This is not actually an issue. In 51 we already have create/update/remove methods in ContextualIdentityService: https://hg.mozilla.org/releases/mozilla-beta/file/tip/toolkit/components/contextualidentity/ContextualIdentityService.jsm

**Comment by bakulf** [comment]
Plus, in case that version of ContextualIdentityService is not enough, we can overwrite methods, running some code with chrome privileges. This is possible for an addon. This means that, we can overwrite ContextualIdentityService._identities, of some ContextualIdentityService.methods in order to return the correct icons, or different names, etc etc.

Basically, we don't need to have any additional platform/gecko changes for this addon from this point of view.

**Comment by bakulf** [comment]
I think we can close this issue. With my latest patches, the addon works in beta (51).
