### ISSUE TITLE
builtin container list

### ISSUE THREAD

**Issue by staabm** [mozilla/testpilot-containers#432]
Most of the big players in the internet are known for collecting a lot of data.

How do you think about providing a list (provided with the installation of the extension/addon/experiment) of websites which by default are started in separate containers, lets say (facebook, amazon, twitter,...)

that way users which dont even start configuring their custom containers will benefit from better privacy just by installing it.

Of course this can only work when basic issues like the one described in https://jotter.jonathankingston.co.uk/blog/2017/04/04/containers-assignment/ which affect the usability are fixed/handled.

**Comment by jonathanKingston** [comment]
I wrote a **really** big response for this and managed to forget to send it...

In short other people have asked for this (@cpeterso), we have spoke about it before but it's not something we likely could do.

I think however we have the ability to look at alternatives to having a default list.o

---

# Why we probably can't do this

- Lists are hard to manage
  - Infrastructure & Storage
  - Getting an army of people
- Opinion based
  - Websites won't be positive about us categorising their website (especially as containers intent is to block/restrict tracking)
  - Users won't agree either
- Producing only a partial list isn't good
  - Having only popular websites creates some kind of dual society (Mozilla usually position themselves away from this rather than support it)
- User issues
  - Makes users lives harder who want the same site in two containers
  - Wrongly assigned containers will cause confusion/exploits

# What we could talk about instead

- Better management for assignments
- Easier "onboarding" for assignments
  - X number of visits in a container asks the user to subscribe
  - Password manager usage
- Suggestions upon navigation

## Pie in the sky ideas

- Let websites manage this themselves via HTTP Header/meta tag
  - I think this is a non starter as websites likely will fit in two categories:
    a. Social/Spam/Tracking/Malware **abuse** to be in Personal/Working container
    b. Banking/Payments/Ecommerce wishes to be isolated into Finance/Shopping
  - b. is solved broadly by https://wicg.github.io/isolation/explainer.html by @estark37
- Other "onboarding" ideas
  - Allow users to share containers via some import/export process
  - URL for RSS-like subscriptions of lists
    - "Hey, your friend Jodi always opens Google in a Personal container [approve]"
    - "The EFF suggest using a Finance container for BankOfAmerica [approve]"

**Comment by groovecoder** [comment]
Good ideas both @staabm and @jonathanKingston but I'm certain we won't do this in the Test Pilot experiment. Like @jonathanKingston - we will probably never do it. The ideas here are cool though, and more comments are welcome.

But I'm closing this to make it clear we won't put it into any future iteration of the experiment.
