### ISSUE TITLE
hide tabs != close tabs

### ISSUE THREAD

**Issue by bakulf** [mozilla/testpilot-containers#46]
When we click on the hide/show image, we close all the container tabs of a kind. When we re-click that icon we show them again. This is wrong for several reasons: sessions are gone, content is reloaded, etc etc.

We should actually *hide* the tabs. This can be done in a interesting way: using an hidden window and swap the docShells of the tab. Then, we have to suspend media elements in that tab. This can be done setting nsIDOMWindowUtils.mediaSuspend to nsISuspendedTypes::SUSPENDED_PAUSE_DISPOSABLE.

**Comment by johngruen** [comment]
Let's put this in stretch, and I'll open a ticket for a survey question regarding the hide behavior.

**Comment by TanviHacks** [comment]
I would prefer that the tab is closed.  A person may "Hide Containers" often, and leave a task behind for a week or more.  If those tabs are not closed, there will still be network requests that take up bandwidth and code running on those pages that impact performance and CPU usage.  Hence, I prefer we close the tabs completely.  Unless we can figure out a way in Gecko to really "pause" everything about that tab.

**Comment by kjozwiak** [comment]
I agree with Tanvi's comment regarding closing the tabs rather than hiding them. We should try avoiding anything that might impact performance for users with slower machines.

One possible way to make this easier on users is to give them the ability to unhide individual tabs. With the current implementation, a user would have to restore all his tabs in a particular container just to view one or two tabs, and then hide them all again.. This doesn't seem like good UX.

Users should be able to open hidden tabs via:

* "show these container tabs" which loads the entire list in the appropriate container, which is already implemented
* Click on a particular tab within the list to open tabs individually

However, this doesn't solve the session issue baku originally mentioned :/

**Comment by bakulf** [comment]
Let's close this bug and file a new one for opening tabs when clicked.

**Comment by kjozwiak** [comment]
@bakulf, I created #137 but I don't have the permissions to close issues.
