### ISSUE TITLE
Wording could be more obvious

### ISSUE THREAD

**Issue by hobarrera** [mozilla/testpilot-containers#492]
I really love containers, and have started spreading the word around coworkers (tech people, so they'll get it).

While tech users will [generally] always get what all this is about, something that we all seem to have agreed upon, is that the wording isn't very newbie-friendly. The the first thing the users sees doesn't make it attractive, and they've skipped the first wizard, all bets are off.

The first time you click the button the big text says _"A better way to mange all the things you do online"_. That doesn't really say anything, and doesn't capture attention. Something like _"Now you can open two sessions on one site at once"_, or _"Keep separate work and personal profiles colour-separated"_ might capture initial attention better. Even though container is about a lot more than that, you need something catchier to grab most people's attention.

**Comment by jonathanKingston** [comment]
@groovecoder is shield something we could use for this?

**Comment by groovecoder** [comment]
Yeah, good call. Thanks for the feedback @hobarrera.

@ChenMorpheus - something to keep in mind while we create the on-boarding variations for the shield study.

**Comment by johngruen** [comment]
@groovecoder @hobarrera i think this is a good suggestion, but there are a few complications:
* Terminology like _session_ is actually pretty technical, if this were going to be a wide audience feature we probably couldn't use such language
* Describing specific use cases in on boarding is tricky b/c if it's not _my_ use case, i may dismiss the product as not for me.

You're 100% right about the watered down language though. We're about to run an experiment on general release Firefox users where we A/B test a new on-boarding that focuses more on the security promises of Containers against the current version. I'm going to go ahead and close this bug since we're  about to get a bunch of data from this test that will give us a clearer answer about the direction we should take.

**Comment by johngruen** [comment]
Fixed by #498
