### ISSUE TITLE
Assignment confirmation page changes

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#500]
See https://docs.google.com/document/d/1zrk_M8Adqc05jMlgPFc0fyUdEysApCY3SO1QPpgT3gM/edit ...

The UI redesign tries to allow users open the site in the current container. (https://github.com/mozilla/testpilot-containers/issues/422)

<img width="632" alt="image" src="https://cloud.githubusercontent.com/assets/71928/25915753/151244f2-3588-11e7-9547-7a07ba24498b.png">

**Comment by jonathanKingston** [comment]
Probably makes sense for me to work on this

**Comment by jonathanKingston** [comment]
Still interim, however @ChenMorpheus are you ok with bolding in the buttons?

![selection_632](https://cloud.githubusercontent.com/assets/338988/26253102/169c7558-3caa-11e7-8906-a936903cadce.png)


@groovecoder gonna have to guess the favicon for that icon there... which is ok for the prototype. I opened another bug for querying a URLs icon.

**Comment by ChenMorpheus** [comment]
@jonathanKingston 
The bolding looks perfect! It emphasizes the difference. Besides, I was wondering if we can display both the tab title and the URL to make it easier to identify for general users. Please find the attached image for instance. 

![group 16](https://cloud.githubusercontent.com/assets/18019946/26291933/9b664e12-3ee4-11e7-94bc-4abbf54566cc.png)

Last but not least, now we're waiting for style review by Stephen because of Shield study. We'll release the measurement once it confirms.

**Comment by jonathanKingston** [comment]
To my knowledge we don't show speculative content like this anywhere else.
The favicon might still be an issue too.

The title would require us to load the content which kinda mitigates the
reason we have the warning in the first place.

Also in web extensions I can't load the page in a one time use private
iframe, so it would mean the page would need to load in default or in a
container.

If this becomes native/or we get better APIs, we might be able to show
cached​ content or another solution.

What do you think @groovecoder?
