### ISSUE TITLE
Container icons missing in shield mode

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot-containers#586]
![tp-containers-icons-missing](https://user-images.githubusercontent.com/71928/27147084-26dc2ca4-5101-11e7-9036-bf00335f2e14.gif)

**Comment by jonathanKingston** [comment]
Hmm this looks like it's not acting acting like a normal embedded addon.

**Comment by kjozwiak** [comment]
@groovecoder, I can reproduce this pretty easily as well.. Simply install the `shield-study-containers.xpi` (used 5b85fc1690fd3b771d3a0a157955e6f4f4c5a231) and you'll notice all the icons are missing from the "+" drop down.

**Comment by jonathanKingston** [comment]
I actually can't replicate this on Ubuntu.
Is this only using the build xpi? That didn't work for me I got node errors.

**Comment by groovecoder** [comment]
Yes, try `npm run build-shield` and then install the `shield-study-containers.xpi` add-on. Did you `npm install && npm install -g shield-study-cli` before building the shield add-on? If so, pastebin error output?

**Comment by kjozwiak** [comment]
> I actually can't replicate this on Ubuntu.

@jonathanKingston, check `about:support` and make sure you're running `@shield-study-containers` and not `@testpilot-containers`. @groovecoder mentioned that if you don't change `"name": "testpilot-containers" ` into `"name": "shield-study-containers"` under the package.json when using the `shield run . -- --binary Nightly` method, you might be running the test pilot instead of the shield study. I ran into this yesterday when I tried to reproduce this using `shield run . -- --binary Nightly`.

Using the XPI, I managed to reproduce this on all three platforms:

* macOS 10.12.5 x64 - Reproduced
* Ubuntu 16.04.2 LTS x64 - Reproduced
* Win 10 Pro x64 - Reproduced
