### ISSUE TITLE
Refreshing a website assigned to a different container wrongly opens the "Containers confirm navigation" page in a new tab

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/testpilot-containers#635]
**[Affected versions]:**
- Firefox 54 and up
- Containers Experiment Build: 2.4.0

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Containers Experiment is installed on a new browser profile.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites.
2. Open the same website in 2 different containers.
3. Assign the website to always open in the first container.
4. Refresh the page in the second container.
5. Observe the results.

**[Expected results]:**
- Container confirm navigation tab, replaces the page for which the refresh was made.

**[Actual results]:**
- After the page refresh is initialized, the "Container confirm navigation" page is opened in a new tab.

**[Notes]:**
- Attached a screen recording of the issue:
![refresh in the same tab](https://user-images.githubusercontent.com/9248513/27475317-62b89ad8-580d-11e7-8166-48d6612f1300.gif)

**Comment by ArchangeGabriel** [comment]
I would say that the opening in a new tab is expected, unless a way to switch a tab from container has been implemented.

However, the issue I see here is that the new tab is not in the right container.

**Comment by jonathanKingston** [comment]
This seems a lot like: #626 I guess we didn't fix it there?
Will check this out anyway.

**Comment by jonathanKingston** [comment]
Sorry I understand this now, it is kinda expected.

Currently we allow "Exemptions" to assignment, issues I see with this related to this and other bugs that might come up:

1. Exemptions are not stored, which means on session restore the approve screen will show
2. On refreshing existing tabs the exemptions are not added on assignment to the exemption list.
3. Exemptions don't persist on opening a new tab (ctrl+click etc)

The issue here is 2. and I think we can fix this when the user assigns the tab.
1. and 3 I'm not sure are going to be solvable.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Containers add-on built on 6/28/2017.
