### ISSUE TITLE
Problems With Menu

### ISSUE THREAD

**Issue by colorinplatinum** [mozilla/testpilot-containers#689]
I believe #687 brought up this issue (in Spanish) but I am having the same problem. When I hover my mouse over the new tab button, the menu doesn't drop down to give me the container option. Similarly, right clicking a link doesn't give me the option to open it in a container either. Firefox tells me the program is up to date and installed but it doesn't work. I have uninstalled and reinstalled but still no luck.

**Comment by azizLIGHT** [comment]
I'm having the same issue on Firefox 54.0 (64-bit) on Ubuntu 14.04 x64 with Containers Experiment 2.4.0. When I put the mouse over the + icon, I used to see a menu appear that would list my containers. Clicking an option there would create a new tab for the selected container. This menu no longer appears and there is no longer an easy way to create specific container tabs, unless you dig through menus or use the toolbar icon

**Comment by DHowett** [comment]
Try clicking and holding the New Tab button. I think they're piloting a new interaction.

It's not necessarily a great one, but I cannot locate a venue in which to state that. :grin:

**Comment by DHowett** [comment]
Tracked in #685.

**Comment by jonathanKingston** [comment]
This is an intentional change as mentioned to move to Long press instead of the hover due to users finding it opening unintentionally. We allow you to change this to a click to open which might be more preferred by changing in about:config `privacy.userContext.longPressBehavior` to "1".

Thanks, please let me know if this isn't the issue.
