### ISSUE TITLE
Can we do something about the context menu entry?

### ISSUE THREAD

**Issue by emmyemi** [mozilla/testpilot-containers#711]
While I like having easy access to the "Always open in ..." feature via the context menu, the current way this is handled is rather ugly-looking, especially with other menu entries surrounding it. Example:

![screenshot](https://user-images.githubusercontent.com/14862440/28948639-fe9bb510-7884-11e7-8ecd-b8087e87763a.png)

Instead, maybe we could change the icon to the left to a version of the extension icon with a colored checkmark overlayed or something. Perhaps the entry could be changed to read "Opening in `x` container" or "Do not open in ..." when the option has been selected instead, that way the checkmark won't be necessary. This isn't exactly a high priority thing, but a more elegant solution would be much appreciated.

**Comment by jonathanKingston** [comment]
Valid points, there is a limitation on the space and also that we can't have a top level tick like check spelling has. We also have the limitation of not always being present due to timing of when the context loads and us looking through our storage to check if the page was assigned.

This leaves us with trying to think of new text (which we tried but nothing could be agreed on / was too long).

Another option is open the prompt instead where you can now assign there. So the text could just read "manage container". (we could also jump this to the edit container screen where you can see the current assigned containers, we could also have an add button there also). This would be an extra click but it could be more useful.

The last option I can think of is making it have a child menu like "languages" does in the screenshot and provide more than just the assignment functionality.

**Comment by emmyemi** [comment]
> Another option is open the prompt instead where you can now assign there. So the text could just read "manage container". (we could also jump this to the edit container screen where you can see the current assigned containers, we could also have an add button there also).

I think this would be much more useful, as you said, and certainly easier on my OCD. 


> The last option I can think of is making it have a child menu like "languages" does in the screenshot and provide more than just the assignment functionality.

Though this could also work just as well. Anything would be a bit better than current, IMO.

**Comment by jonathanKingston** [comment]
@groovecoder pick one and I can implement, I think the top one won't be possible until 55 (which we will likely wait for anyways). Unless you think design should be involved.

**Comment by groovecoder** [comment]
Yeah, let's have @ChenMorpheus and/or @fangshih make the call here.

**Comment by ChenMorpheus** [comment]
Hi @jonathanKingston @groovecoder, please find the proposals below. The original solution was in my previous spec. If it's not feasible, then we can go with solution B. However, if it's mandatory to have icon for every add-on, then we can go with solution C. What do you think?

![group 16](https://user-images.githubusercontent.com/18019946/29112654-1a864632-7d21-11e7-85e1-2326f86d2bce.png)

**Comment by jonathanKingston** [comment]
@ChenMorpheus solution C is the only possible.

This makes me happy!

@emmyemi is this better?

**Comment by emmyemi** [comment]
@jonathanKingston That looks great! :D

**Comment by alekksander** [comment]
is it disabled now? i cannot see it in context menu anywhere…

**Comment by grahamperrin** [comment]
I see no option to move a _single_ tab to a new window. 

Please, have I misunderstood the mock-ups? Or is the intention to encourage no more than one window per container?

**Comment by jonathanKingston** [comment]
> I see no option to move a single tab to a new window.

I would rather a simple context menu. The more we have the less people will use it. Given that dragging a tab out of the dock is just as easy I don't think this makes sense to dedicate a menu item to it.

> Or is the intention to encourage no more than one window per container?

I don't think that is the intention really, it just gives people quick access to move the tabs for the current container into it's own window. I'm not entirely sure how useful it is at all let alone adding more options.
