### ISSUE TITLE
Containers name

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/testpilot-containers#763]
@groovecoder this is a discussion issue.

"Mozilla containers" is the current new extension name. I was thinking that we might be "Firefox containers center" or something equally "firefox" and also more than just containers alone.
My rationale is that actually containers is a platform feature and  other addons can provide the same functionality so encapsulating the whole brand might be a little confusing like as if it will remain a barrier to using containers like it is currently in non 57.

**Comment by groovecoder** [comment]
"Mozilla Containers" or "Firefox Containers" are fine with me. I picked "Mozilla Containers" first just to show "this is the Containers add-on created by Mozilla"

Picking the right name may be part of a larger strategy to improve & enhance our official Mozilla presence on AMO.

**Comment by jonathanKingston** [comment]
Should we check with Marketing for this @groovecoder it's going to require a package update anyway

**Comment by hoosteeno** [comment]
I'm glad we're having this conversation. Forgive the length of this comment.

> Picking the right name may be part of a larger strategy to improve & enhance our official Mozilla presence on AMO.

I agree with groovecoder. We have an opportunity with this launch to position a category of first-party extensions that come with extra assurances and/or get additional marketing (e.g. in-product CTAs). Naming is the first signal: "ExtensionName by Mozilla", for example. We might also create an AMO collection (e.g. [Ad Blockers](https://addons.mozilla.org/en-US/firefox/collections/mozilla/ad-blockers/)) for first-party extensions and promote it wherever convenient.

If Containers is a platform feature then calling our extension Containers as well will make it harder to market each. For example, we'll have two pages competing for Containers search -- one for developers and one for consumers (See "[browser](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/browser)" for an example of the trouble this can create).

Finally, we have an opportunity to give this extension a name that is unique and has some value for consumer marketing. We can use search as a signal for how people who want this exact capability actually talk about it. 

Appx. 350k people search every month for "containers". They generally want Rubbermaid boxes or similar -- they're not looking for a browser, and our marketing will be lost in those results. Nobody searches for "browser containers" because nobody knows what that means. Same for "account tabs". 6,500 people search for "two accounts", which speaks to a specific intent and use case we address. Fewer than a hundred each month search for "profile tab" and "identity tab", which make the use case more generic. 

165,000 people every month search for "multi-account", and [those search results](https://www.google.com/search?q=multi-account&pws=0) reveal a lot of apps etc. that enable multiple accounts in _________. That's what people who want this capability search for. Calling it "Multi-Account Browser Tabs by Mozilla" would almost guarantee us a trickle of search traffic, and it's a name that apparently resonates with the people most likely to want a feature like this.

**Comment by jonathanKingston** [comment]
My understanding is we can't use "Mozilla" as a prefix based on the new guidelines which was another reason for the question.

Is the issue with the exposure of the "by Mozilla" second line on AMO? Lightbeam for example is already "by Mozilla" - https://addons.mozilla.org/en-US/firefox/addon/lightbeam/ but not in it's addon name.

Given previous comments can "Multi-Account Browser Tabs by Mozilla" be "Multi-Account Tabs"? or "Multi-Account Tabs for Firefox" to match Lightbeam.

Agreed with promoting collections (we spoke at all hands having a set section for Mozilla addons even), I also have a containers collection I am trying to promote too: https://addons.mozilla.org/en-US/firefox/collections/jkt/container-addons/ ones that are still secure in how they behave.

**Comment by Kiiirby** [comment]
Hi! I checked in with the brand team to make sure they're on board. We have a contact on that team who can weigh in if we want naming guidance. When we have a name we like, we may need to file a legal bug to get the official green light. 

If there are naming guidelines specific to AMO, can you share them here?

Is there a shortlist of names you're choosing between?

Thanks!

**Comment by groovecoder** [comment]
I like the idea of dropping "Mozilla" out of the add-on name so it shows
just once on the AMO page.

Using "Firefox" in the name lends our official seal on it.

Do we want to promote the built-in Containers feature outside of this
add-on? It seems our strategy is to shift users from the built-in
Containers implementation to this add-on. In that case, "Firefox
Containers" with "by Mozilla" implied/express on AMO seems good.

Justin - is 'Firefox Containers' okay if we optimize the AMO page contents
towards "multi-account" terms?

Maybe "Firefox Multi-Account Containers" ?

**Comment by jonathanKingston** [comment]
> Do we want to promote the built-in Containers feature outside of this add-on?

It's a platform feature that every containers addon will depend on, there isn't anything less containers about the addons listed here: https://addons.mozilla.org/en-US/firefox/collections/jkt/container-addons/
I would argue it should be a term reserved much like "tabs" isn't specific to one tab addon.
The changes made in central actually make the native features more visible, this addon is just a few UX decisions on top of the existing interface.

So perhaps we won't promote other addons however I don't think this addon should "own" containers as a whole. Perhaps parts of it's interface will replace what is in about:preferences#containers but I don't think we should make a big fan fair about this over any of the community addons.

For this reason I like the idea we might even drop the word containers from this addon in total and use it just in the description.

> Maybe "Firefox Multi-Account Containers" ?

"Multi-Account Containers for Firefox" or "Multi-Account Tabs for Firefox" would be my diretion.

**Comment by Kiiirby** [comment]
How about: Firefox Multi-Account Containers / by Mozilla
Lightbeam would become Firefox Lightbeam / by Mozilla
With "by Mozilla" in the byline.
We'd use this naming convention in the future to give all Mozilla-built add-ons a stronger tie in.
The brand team suggested this and I recommend it. Let's use these names if there are no objections.

**Comment by hoosteeno** [comment]
I support the good naming ideas we have here. I foresee minor confusion on the part of people who have already fallen in love with Containers (the feature). Suggest we anticipate this with a change to our testpilot page: https://github.com/mozilla/testpilot-containers/issues/785

**Comment by jonathanKingston** [comment]
Cool, thanks both! This should now be fixed when https://github.com/mozilla/testpilot-containers/pull/786 lands. Will change [Lightbeam](https://github.com/mozilla/lightbeam-we/) now.

**Comment by grahamperrin** [comment]
I was not confused by _the change_ of name. 

However when I first saw the most recent name, I immediately thought, it's potentially confusing; does not help to understand the feature set. 

A _Firefox Account_ is **definitely** this: 

- https://www.mozilla.org/firefox/accounts/

> With a Firefox Account, you can get all your bookmarks, passwords, open tabs and more …

So I'd expect _Firefox Multi-Account_ to be for people who use more than one _Firefox Account_.

**Comment by TriMoon** [comment]
I think the extension should rather be named either:
  - "auto containers",
  - OR "auto containers per site",

**THOSE** name accurately resembles the functionality provided by the extension, no confusion possible...
