### ISSUE TITLE
Opening a new window with hidden tabs doesn't work

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/testpilot-containers#797]
In https://github.com/mozilla/testpilot-containers/issues/746#issuecomment-327687807 @falolaf raised:

> I'm now on Firefox Multi-Account Containers 4.0.1. If all tabs for a container are hidden then "Move  tabs to a new window" still does nothing.
>
> I can do "Show this container" and then "Move tabs to a new window".
>
> FF 55.0.3
> Windows 7

And:
> It seems that:
> tabId: list.shift().id
> throws an error. shift() is not a method of list.

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Containers version (4.0.1 built on 09/08/2017). However, when showing the tabs you can observe that each container tab is duplicated as described in #791 

**[Notes]**
- Attached a screen recording of the issue:
![container_new_window_issue](https://user-images.githubusercontent.com/20083658/30209814-8e1d779e-94a2-11e7-8bfb-35f639124e21.gif)
