### ISSUE TITLE
What about if the user wants to create a container with an empty name?

### ISSUE THREAD

**Issue by bakulf** [mozilla/testpilot-containers#83]
Should we show an alert? Or we want to show a message?

**Comment by ChenMorpheus** [comment]
I would propose to provide "Container 01" as default name since the user might want to quickly create a container. Besides, we'll have a blinking text cursor to remind the user inputing a name. If the user wants to create more and more containers without inputing names, we can simply add the number to "Container 02", "Container 03", etc. I have concerns that displaying an alert or a message might interrupt the user flow.  What do you think?
![2 1 container create name]

(https://cloud.githubusercontent.com/assets/18019946/21974730/89d5e7be-dc03-11e6-89fb-98691e9dd46b.png)
