### ISSUE TITLE
What should we do if the popup containers menu gets too tall?

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot-containers#92]
should we overflow it? scroll?

**Comment by ChenMorpheus** [comment]
@johngruen @groovecoder @TanviHacks If I understand correctly from the discussion in InVision([link](https://mozilla.invisionapp.com/d/main#/projects/prototypes/9751862/comments?inbox=true&inboxProjectID=9751862&inboxConversationID=76450660)), the pop-up will always fix at that height and impact any following slide- overs if we expand the pop-up's maximum height based on 7 or so containers in it. That means the shorter content will look bad, especially for edit and detail slide-overs. 

We assume that users won't create more than 6 containers in general use, and that's why we decided to fix the height of 6 containers to make it usable and look nice at the same time. As a result, I'll propose to have scroll as default, and we can decide if increasing or keep the number once we get the average data after release. What do you think?

**Comment by bakulf** [comment]
I implemented a fix size for the panel. When there are too many containers, the list of containers is scrollable. I think the current implementation works better with proposal 2 (and I also like more this proposal).

**Comment by groovecoder** [comment]
Check what happens when the list of tabs gets really tall.
